### ISSUE TITLE
tc:dev serverinfo

### ISSUE THREAD

**Issue by HrKnuddel** [toolchestbot/toolchest-help#2]
Red kennt den Felher... wollte nur ihn notieren

**Comment by RedCrafter07** [comment]
Danke für deine Hilfe ^^
Wir werden uns darum kümmern.

**Comment by RedCrafter07** [comment]
Er wurde indirekt behoben. Es lag an Speicherungsfehlern des Bots, die behoben sind.

**Comment by RedCrafter07** [comment]
Gibt es noch was, wo wir helfen können?

**Comment by RedCrafter07** [comment]
Dann schließe ich das ganze :)

**Comment by olebohmbach** [comment]
Das war wohl ein Nein xD

**Comment by revoX-Development** [comment]
Huch, was ist den hier los?
