### ISSUE TITLE
Ticket-Archivierung

### ISSUE THREAD

**Issue by HrKnuddel** [toolchestbot/toolchest-help#3]
Beim Ticket System eine Archivierungs System

**Comment by RedCrafter07** [comment]
Hallo,
wie stellst du dir das vor?

**Comment by HrKnuddel** [comment]
Wenn man das Ticket schließt wird entweder eine Datei erstellt, in der die Aufzeichnug steht, oder der Kanal wird in eine andere Kategorie verschoben

**Comment by RedCrafter07** [comment]
Hmm, ich würde die Schreibrechte einfach entziehen.

**Comment by HrKnuddel** [comment]
Kann man auch mit dazu machen

**Comment by RedCrafter07** [comment]
Ok, dann machen wir es so.

**Comment by RedCrafter07** [comment]
Ich schreibe es mal auf die Todo ^^

**Comment by RedCrafter07** [comment]
Ich sollte es vielleicht mal auf die Todo-Liste hinzufügen...

**Comment by RedCrafter07** [comment]
Wie schnell möchtest du (ungefähr), dass wir die Funktion umsetzen?

**Comment by jonasnp5** [comment]
Wird gemacht.
