### ISSUE TITLE
Commands sind alle doppelt registriert und funkionieren alle nicht

### ISSUE THREAD

**Issue by olebohmbach** [toolchestbot/toolchest-help#6]
![image](https://user-images.githubusercontent.com/77053238/140643787-377c8ede-babb-4ed8-9e44-53fd10847f58.png)
![image](https://user-images.githubusercontent.com/77053238/140643788-85e748f9-fba2-4007-8e24-20fcb60aab74.png)

**Comment by olebohmbach** [comment]
[Screenshots von MGTV's Server]

**Comment by RedCrafter07** [comment]
Vielen Dank. Wir werden uns in Kürze darum kümmern.

**Comment by revoX-Development** [comment]
Das, die Doppelt sind, ist ein Discord Bug, damit die Commands funktionieren, brauch der Bot höhere Berechtigungen, joine am besten mal unserem Discord Server (https://toolchestbot.xyz/discord) dann können wir dir besser helfen

**Comment by jonasnp5** [comment]
@Ole-is-live Die Bugs und Fehlern wurden behoben. 
Das TC Team bedankt sich bei Ihnen für ihre Geduld und Meldung.
